### ISSUE TITLE
Crash and Compilation Error on Windows

### ISSUE THREAD

**Issue by kasumikira** [ChefKissInc/QEMUAppleSilicon#260]
### Operating System

Windows 11 25H2

### What is your CPU's model?

AMD Ryzen 9 7940H

### Describe the unexpected behaviour in detail.

https://github.com/ChefKissInc/Inferno/blob/70dad7c1a7900bf68be318eb29132a5fe7587484/system/cpus.c#L496
This line makes compilation fail on windows. It seems that the sem has been removed and is only used in qtest.

Also, this commit https://github.com/ChefKissInc/Inferno/commit/e0bf8bd7001752b746bb364fe023c49746dc8689 makes the emulator crash on windows. The only two lines on my terminal before the crash are:
```
**
ERROR:../hw/pci/pci.c:2849:pci_device_class_base_init: assertion failed: (conventional || pcie || cxl)
Bail out! ERROR:../hw/pci/pci.c:2849:pci_device_class_base_init: assertion failed: (conventional || pcie || cxl)
```
Reverting this commit fix the issue.

### What should've happened instead?

No compilation errors. No crash.

### Issue Report Terms

- [x] You have made sure that there are no other reports about this bug.
- [x] You do not use any software that might interfere with correct function of this software. For Hackintosh users, that could be OCLP, WEG, etc.
- [x] You are on the latest commit of the emulator.
- [x] You acknowledge that violation of these terms may result in your issue being closed or you getting blocked from the organisation.

**Comment by VisualEhrmanntraut** [comment]
@kasumikira does https://github.com/ChefKissInc/Inferno/commit/8e2eef42b0e0a0b564eb4450e909a6e870038c66 fix it?
